### ISSUE TITLE
[FEATURE] - Process goca flags from config file or similar

### ISSUE THREAD

**Issue by Xumeiquer** [Gocaio/goca#12]
Goca should use some configuration file in terms to avoid using flags. But this does not mean flags should be removed.

A good library which could be used is [viper](https://github.com/spf13/viper).

**Comment by gonzalezkrause** [comment]
What should be configured with a configuration file? and please, can you give an example of this configuration file.

btw/ viper is the best choice for this configuration files, Goca v.0.3.0 already makes use of Cobra, this means that the integration with Viper is for free ;)

**Comment by Xumeiquer** [comment]
The configuration file could be interesting for some "static" flag options. For example, `ua` or `timeout` or even `url`.

The configuration file could be used as custom defaults and then customized using command line flags.

An example could be something like this.
```json
{
    "ua": "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0",
    "timeout": 60,
    "project": "default_project",
    "url": "my-company.url",
}
```

**Comment by joanbono** [comment]
Something like:

```toml
# filename: config.toml
[config]
userAgent = "Goca Metadata Scanner"
loglevel = "info"
threads = 1
plugins = "all"

[database]
file = "goca.db"

[dorker]
engines = "all"
pages = 1
save = true
threshold = 0

[scraper]
depth = 1
domain = "goca.io"
save = true
threshold = 0
```
